[package]

name = "StringTheory"
version = "0.0.1"
authors = ["HiroLord <prestonturner42@gmail.com>", "Nathan Braswell <miloignis@gmail.com>", "Marcus Godwin <marcusgodwin@hotmail.com>"]


[dependencies]
sdl2 = "0.0.24"
rustnet = "0.0.1"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.rust-assimp]
git = "https://github.com/lotusronin/rust-assimp"
