[package]

name = "StringTheory"
version = "0.0.1"
authors = ["HiroLord <prestonturner42@gmail.com>", "Nathan Braswell <miloignis@gmail.com>"]


[dependencies]
sdl2 = "0.0.24"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.rustnet]
git = "https://github.com/HiroLord/rustnet"
